"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { useEffect, useState } from "react";
import { api, clearStoredSession, getApiErrorMessage, isUnauthorized } from "../../lib/api";
import { EmployeeAiAssistant } from "./hr-ai-assistant";
import { NotificationBell } from "./notification-bell";

type Report = { summary?:string; strengths?:string[]; weaknesses?:string[]; matched_keywords?:string[]; missing_keywords?:string[]; section_feedback?:{section:string;feedback:string}[]; ats_issues?:string[]; bullet_rewrites?:string[]; improved_summary?:string; action_plan?:string[] };
type Analysis = { id:number; original_filename:string; job_title:string; overall_score:number; impact_score:number; clarity_score:number; ats_score:number; status:string; recommendations:string[]; detailed_report:Report; created_at:string };

export function ResumeReportDetail({ id }: { id:string }) {
  const router=useRouter(); const [analysis,setAnalysis]=useState<Analysis|null>(null); const [initials,setInitials]=useState("EU"); const [error,setError]=useState(""); const [downloading,setDownloading]=useState(false);
  useEffect(()=>{api.get<Analysis>(`/api/resumes/analyses/${id}/`).then(({data})=>setAnalysis(data)).catch((reason)=>{if(isUnauthorized(reason)){clearStoredSession();router.replace("/");return;}setError(getApiErrorMessage(reason,"This report could not be loaded."));});},[id,router]);
  useEffect(()=>{api.get<{full_name:string}>("/api/auth/profile/").then(({data})=>setInitials(data.full_name.split(" ").map((part)=>part[0]).slice(0,2).join("").toUpperCase()||"EU")).catch(()=>undefined);},[]);
  async function download(){if(!analysis)return;setDownloading(true);try{const response=await api.get(`/api/resumes/analyses/${id}/download/`,{responseType:"blob"});const url=URL.createObjectURL(response.data);const anchor=document.createElement("a");anchor.href=url;anchor.download=analysis.original_filename;anchor.click();URL.revokeObjectURL(url);}catch(reason){setError(getApiErrorMessage(reason,"The resume could not be downloaded."));}finally{setDownloading(false);}}
  if(error)return <main className="grid min-h-screen place-items-center bg-slate-50 p-6"><div className="text-center"><h1 className="text-xl font-bold">Report unavailable</h1><p className="mt-2 text-sm text-slate-500">{error}</p><Link href="/employee/reports" className="mt-5 inline-flex rounded-lg bg-blue-700 px-4 py-2 text-xs font-bold text-white">Back to history</Link></div></main>;
  if(!analysis)return <main className="grid min-h-screen place-items-center bg-slate-50 text-sm font-semibold text-slate-500">Loading full report...</main>;
  const report=analysis.detailed_report||{}; const hasDetails=Boolean(report.summary);
  return <main className="min-h-screen bg-[#f7f8fa] text-slate-950"><header className="sticky top-0 z-20 flex h-16 items-center justify-between border-b border-slate-200 bg-white px-5 sm:px-8"><div className="flex items-center gap-4"><Link href="/employee/resume-analyzer" className="rounded-lg border border-slate-200 px-3 py-2 text-[10px] font-bold text-slate-600 hover:text-blue-700">← Resume Analyzer</Link><div><strong className="block text-xs">Resume report</strong><span className="text-[9px] text-slate-400">{analysis.original_filename}</span></div></div><div className="flex items-center gap-2"><button type="button" disabled={downloading} onClick={()=>void download()} className="rounded-lg border border-slate-200 bg-white px-4 py-2 text-[10px] font-bold text-slate-700">{downloading?"Downloading...":"Download resume"}</button><Link href="/employee/resume-analyzer/new" className="rounded-lg bg-blue-700 px-4 py-2 text-[10px] font-bold text-white">New analysis</Link><NotificationBell/><span className="grid size-8 place-items-center rounded-full bg-blue-50 text-[10px] font-bold text-blue-700">{initials}</span><EmployeeAiAssistant reportId={analysis.id} reportName={analysis.original_filename}/></div></header>
    <div className="border-b border-slate-200 bg-white px-5 pb-3 sm:px-8"><input aria-label="Search report" placeholder="Search this report..." className="h-9 w-full max-w-xs rounded-lg bg-slate-50 px-3 text-xs outline-none focus:ring-2 focus:ring-blue-100"/></div>
    <div className="mx-auto w-full max-w-[1500px] px-5 py-4 sm:px-6"><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-col justify-between gap-4 md:flex-row md:items-center"><div><p className="text-[9px] font-bold uppercase tracking-[.18em] text-blue-600">Analysis complete</p><h1 className="mt-1 text-xl font-bold">{analysis.job_title}</h1><p className="mt-0.5 text-[10px] text-slate-500">{analysis.original_filename}</p></div><div className="flex items-center gap-3"><span className="grid size-16 place-items-center rounded-xl bg-blue-50 text-2xl font-bold text-blue-700">{analysis.overall_score}</span><div><strong className="block text-sm">{analysis.status}</strong><span className="text-[10px] text-slate-500">Overall resume score</span></div></div></div><div className="mt-4 grid gap-3 border-t border-slate-100 pt-4 sm:grid-cols-3"><Score label="Impact" value={analysis.impact_score}/><Score label="Clarity" value={analysis.clarity_score}/><Score label="ATS match" value={analysis.ats_score}/></div></section>
      {!hasDetails?<section className="mt-5 rounded-2xl border border-amber-200 bg-amber-50 p-6"><h2 className="font-bold text-amber-950">Detailed report unavailable</h2><p className="mt-2 text-xs text-amber-800">This analysis was created before detailed reports were introduced. Analyze the resume again to generate the expanded report.</p><Link href="/employee/resume-analyzer" className="mt-4 inline-flex rounded-lg bg-amber-900 px-4 py-2 text-[10px] font-bold text-white">Analyze again</Link></section>:<div className="mt-5 space-y-5"><Card title="Executive summary"><p className="text-xs leading-6 text-slate-600">{report.summary}</p></Card><div className="grid gap-5 lg:grid-cols-2"><ListCard title="Strengths" items={report.strengths}/><ListCard title="Areas to improve" items={report.weaknesses}/></div><div className="grid gap-5 lg:grid-cols-2"><Tags title="Matched keywords" items={report.matched_keywords} green/><Tags title="Missing or underused keywords" items={report.missing_keywords}/></div><Card title="Section-by-section feedback"><div className="grid gap-3 md:grid-cols-2">{report.section_feedback?.map((item,index)=><div key={index} className="rounded-xl border border-slate-200 p-4"><strong className="text-xs">{item.section}</strong><p className="mt-2 text-[10px] leading-5 text-slate-500">{item.feedback}</p></div>)}</div></Card><div className="grid gap-5 lg:grid-cols-2"><ListCard title="ATS and formatting issues" items={report.ats_issues}/><ListCard title="Suggested bullet rewrites" items={report.bullet_rewrites}/></div><Card title="Improved professional summary"><p className="rounded-xl bg-blue-50 p-4 text-xs leading-6 text-blue-950">{report.improved_summary}</p></Card><Card title="Prioritized action plan"><ol className="grid gap-3 md:grid-cols-2">{report.action_plan?.map((item,index)=><li key={index} className="flex gap-3 rounded-xl border border-slate-200 p-4 text-[10px] leading-5 text-slate-600"><b className="grid size-6 shrink-0 place-items-center rounded-full bg-blue-700 text-white">{index+1}</b>{item}</li>)}</ol></Card></div>}
    </div></main>;
}
function Score({label,value}:{label:string;value:number}){return <div><div className="flex justify-between text-xs"><span className="text-slate-500">{label}</span><b>{value}/100</b></div><div className="mt-2 h-2 rounded-full bg-slate-100"><div className="h-full rounded-full bg-blue-600" style={{width:`${value}%`}}/></div></div>}
function Card({title,children}:{title:string;children:React.ReactNode}){return <section className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><h2 className="mb-3 text-sm font-bold">{title}</h2>{children}</section>}
function ListCard({title,items=[]}:{title:string;items?:string[]}){return <Card title={title}><ul className="space-y-3">{items.map((item,index)=><li key={index} className="flex gap-3 text-[11px] leading-5 text-slate-600"><span className="mt-1 size-2 shrink-0 rounded-full bg-blue-600"/>{item}</li>)}</ul></Card>}
function Tags({title,items=[],green=false}:{title:string;items?:string[];green?:boolean}){return <Card title={title}><div className="flex flex-wrap gap-2">{items.length?items.map((item)=><span key={item} className={`rounded-full px-3 py-1.5 text-[10px] font-semibold ${green?"bg-emerald-50 text-emerald-700":"bg-amber-50 text-amber-700"}`}>{item}</span>):<span className="text-xs text-slate-400">None identified</span>}</div></Card>}
